In [1]:
import numpy as np
import pandas as pd

In [40]:
df_task = pd.read_excel(r'C:\Users\jcaraan\OneDrive - DXC Production\Jared-kun\JDs\TaskUs\Exercises BIDS 2021.xlsx')
df_task.drop('Unnamed: 11', axis = 1, inplace = True)

df_task['Date'] = pd.to_datetime(df_task['Date'], format = '%Y-%m-%d')

df_task['Month'] = df_task['Date'].dt.month
df_task['Week']  = df_task['Date'].dt.isocalendar().week
df_task['Day']   = df_task['Date'].dt.day
df_task['Dweek'] = df_task['Date'].dt.dayofweek

df_task.drop('Date', axis = 1, inplace = True)

In [7]:
df_task.head()

,Employee ID,Email Address,No Error,M/I Error,Total,Error Rate,TeamLead,Age,Tenure,Shift,Month,Week,Day,Dweek
0,1923351,mark.antonio@jasondaman.com,603,57,660,0.0945,Buckey Barnes,30,7,MID,1,5,31,1
1,5555631,bernard.gana@jasondaman.com,612,57,669,0.0931,Buckey Barnes,45,10,PM,1,3,20,4
2,7838271,reymar.gasparillo@abc.com,727,57,784,0.0784,Buckey Barnes,37,5,MID,4,17,24,0
3,8209713,debonaire.liwanag@jasondaman.com,809,57,866,0.0705,Buckey Barnes,39,2,MID,2,9,27,0
4,6480269,maria.gagarin@jom.com,814,57,871,0.0700,Buckey Barnes,46,9,AM,5,21,27,5

In [41]:
df_Month = df_task.groupby(['Month', 'Day', 'Shift', 'TeamLead'], as_index = False)[['M/I Error', 'No Error']].sum()

In [42]:
df_Month_10 = pd.DataFrame(df_Month[df_Month['Month'] == 10])

In [43]:
df_Month_10['Error_Rate'] = (df_Month_10['M/I Error'] / df_Month_10['No Error']) * 100

In [44]:
df_Month_10

     Month  Day Shift       TeamLead  M/I Error  No Error  Error_Rate
402     10    2   MID   Don De Marco          8       810    0.987654
403     10    4    AM  Buckey Barnes         57       972    5.864198
404     10    4    PM  Joey Jordison         19       786    2.417303
405     10    5    AM  Joey Jordison         10       375    2.666667
406     10    5   MID  Buckey Barnes         20       939    2.129925
407     10    5    PM  Buckey Barnes         57       907    6.284454
408     10    6    AM   Don De Marco         28       469    5.970149
409     10    7    AM  Joey Jordison          6      1184    0.506757
410     10    7    PM  Buckey Barnes          8       823    0.972053
411     10    8    AM  Buckey Barnes         29       326    8.895706
412     10    8    AM   Don De Marco         12       425    2.823529
413     10    8    PM  Joey Jordison         24       615    3.902439
414     10    9    AM  Joey Jordison         24      1026    2.339181
415     10   11    AM   Don De Marco          9       430    2.093023
416     10   12    PM  Joey Jordison         16       460    3.478261
417     10   13   MID   Don De Marco          4       631    0.633914
418     10   14    AM   Don De Marco         10       611    1.636661
419     10   14   MID   Don De Marco          9       488    1.844262
420     10   18    AM  Buckey Barnes         29      1156    2.508651
421     10   19    PM   Don De Marco          9       939    0.958466
422     10   20    AM   Don De Marco          4       311    1.286174
423     10   20    AM  Joey Jordison         15       985    1.522843
424     10   22    AM  Buckey Barnes         22       935    2.352941
425     10   22    PM  Buckey Barnes         19       560    3.392857
426     10   23   MID   Don De Marco         11       414    2.657005
427     10   23    PM  Joey Jordison          4       360    1.111111
428     10   25   MID   Don De Marco         13       662    1.963746
429     10   25    PM   Don De Marco         18      1085    1.658986
430     10   26    AM  Buckey Barnes         45      1948    2.310062
431     10   28    AM   Don De Marco         28       350    8.000000
432     10   28   MID  Joey Jordison         13       454    2.863436
433     10   28    PM  Buckey Barnes         57      1094    5.210238
434     10   28    PM   Don De Marco          9       779    1.155327
435     10   30   MID  Buckey Barnes         13       980    1.326531

In [45]:
df_Month_10.to_excel(r'C:\Users\jcaraan\OneDrive - DXC Production\Jared-kun\JDs\TaskUs\October.xlsx', index = False)